### ISSUE TITLE
2MB ROM / more camera roll slots

### ISSUE THREAD

**Issue by GyroDragona** [untoxa/gb-photo#47]
Would it be possible to have a 2MB ROM opten that would let us have more camera roll slots? I think with that size it would allow up to 15 camera rolls for people that have 2MB of flash ROM space. It would be super helpful.

**Comment by untoxa** [comment]
That is not possible due to hardware limitations.

**Comment by GyroDragona** [comment]
It's not? What is the limiting factor out of curiosity?

**Comment by untoxa** [comment]
MAC-GBD chip.
