### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by GyroDragona** [untoxa/gb-photo#50]
there are a couple things missing that really need to be added to the documentation. How does one actually fill in the owner info. I can't find anything about how to do that or in what instances that the SD card setting can be used and with what hardware. The existaning documentation images seem out of date.

**Comment by untoxa** [comment]
Owner info editor is not implemented yet. SD card camera hardware does not exist yet in wild.

**Comment by GyroDragona** [comment]
![20240730_190237](https://github.com/user-attachments/assets/ff438b8c-6158-4c80-8393-54a39c96e271)
You have an option for it in the menus. It's why I was asking about under what conditions it could be or might be used.
