### ISSUE TITLE
This project needs a documentation

### ISSUE THREAD

**Issue by Raphael-Boichot** [untoxa/gb-photo#6]
I can contribute, but the project needs to be stabilized first. It can typically contain:
- a small storytelling
- a basic user manual with explanation of menus (once stabilized)
- a basic explanation of what registers do in Manual mode (a basic sensor documentation)
- compiling guides for Windows and Linux users
- credits

**Comment by untoxa** [comment]
You are very welcome. Most of the parts may be described already. Also all that service stuff which is already implemented like printing, etc.

**Comment by Raphael-Boichot** [comment]
I think lack of documentation is not an issue now.
